# Generated by Django 3.2.9 on 2021-12-10 03:58

import DharanAPI.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Cédula de ciudadanía')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombres completos')),
                ('apellido', models.CharField(max_length=45, verbose_name='Apellidos Completos')),
                ('sexo', models.CharField(choices=[('m', 'masculino'), ('f', 'femenino'), ('n/d', 'no definido')], default='n/d', max_length=10)),
                ('edad', models.IntegerField(validators=[django.core.validators.MaxValueValidator(125), django.core.validators.MinValueValidator(1)], verbose_name='Edad(Años)')),
                ('telefono', models.CharField(blank=True, max_length=10, verbose_name='Teléfono móvil')),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre del tratamiento')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripción del tratamiento')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Precio(USD)')),
                ('foto', models.ImageField(default='static/img/tratamientos/default.jpg', upload_to=DharanAPI.models.urlimg, verbose_name='Foto referencial')),
            ],
        ),
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Cédula de ciudadanía')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
