# Generated by Django 3.2.9 on 2021-12-05 22:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Cédula de ciudadanía')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombres completos')),
                ('apellido', models.CharField(blank=True, max_length=45, verbose_name='Apellidos Completos')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Cédula de ciudadanía')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombres completos')),
                ('apellido', models.CharField(blank=True, max_length=45, verbose_name='Apellidos Completos')),
                ('sexo', models.CharField(choices=[('m', 'masculino'), ('f', 'femenino'), ('n/d', 'no definido')], default='n/d', max_length=10)),
                ('edad', models.IntegerField(validators=[django.core.validators.MaxValueValidator(125), django.core.validators.MinValueValidator(1)], verbose_name='Edad(Años)')),
                ('telefono', models.CharField(blank=True, max_length=10, verbose_name='Teléfono móvil')),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre del tratamiento')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripción del tratamiento')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Precio(USD)')),
            ],
        ),
    ]
