# Generated by Django 3.2.9 on 2021-12-05 23:56

import DharanAPI.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DharanAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamiento',
            name='foto',
            field=models.ImageField(default='default.jpg', upload_to=DharanAPI.models.urlimg),
        ),
    ]
