# Generated by Django 3.2.9 on 2021-12-05 23:58

import DharanAPI.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DharanAPI', '0002_tratamiento_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamiento',
            name='foto',
            field=models.ImageField(default='static/img/tratamientos/default.jpg', upload_to=DharanAPI.models.urlimg),
        ),
    ]
