# Generated by Django 3.2.9 on 2021-12-06 00:51

import DharanAPI.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DharanAPI', '0003_alter_tratamiento_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='apellido',
            field=models.CharField(max_length=45, verbose_name='Apellidos Completos'),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='foto',
            field=models.ImageField(default='static/img/tratamientos/default.jpg', upload_to=DharanAPI.models.urlimg, verbose_name='Foto referencial'),
        ),
    ]
